data:
  dataset: "papila" # dataset name
  data_dir: ""  # absolute path e.g., "/XXX/medical-calibration-fairness-mllm/data/papila/"
  train_split: "" # e.g., "train.csv" placed in "/XXX/medical-calibration-fairness-mllm/data/papila/splits/"
  val_split: "" # e.g., "val.csv"
  test_split: ""  # e.g., "test.csv"
  image_name_col: "image_name"  # column name for image names, an example entry could be "image_12345.jpg" placed in "/XXX/medical-calibration-fairness-mllm/data/papila/images/"
  # other column names
  patient_age_col: "patient_age"  # column name for patient age
  patient_sex_col: "patient_sex"
  diagnosis_col: "diagnosis"  # column name for labels, e.g., "0" or "1"
  # you can add more here, use them in dataset/__init__.py

sampling:
  n: 1
  temperature: 0.2  # do not change to 0.0, possible unexpected behavior
  top_logprobs: 6
  max_completion_tokens: 1

parsing:
  answer_options: ["negative", "positive"] # [0, 1, ...] order is important
  attributes:  # attributes that will appear in the text query, the order is important, use same names as in the dataset/__init__.py
    b_age: ["age <60", "age >=60"]
    sex: ["male", "female"]  # you can add more attributes
  cared_attribute: ""  # e.g., "sex", select one from parsing.attributes